INVALIDMARKET = "No such market found.\nCorrect format: !market"
INVALIDHELP = "Try using '!help' instead."
INVALIDCLEAR = "Try using '!clear' instead."
INMAX= "Maximum amount of orders per user: {maxorders}"
HELPER = "Correct format: !wtb {currency} {currency2}\nEx. !wtb 1000 500"
HELP = "**Welcome to OTC-Bot!**\n\nCommands:\n!wtb {currency} {currency2}\n!wts {currency} {currency2}\n!market\n!clear\n\nFor buy and sell orders, fill in the {currency2} price **per** {currency}."